name: Upload to vps
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PASSWORD: ${{ secrets.PASSWORD }}
          REMOTE_PORT: ${{ secrets.PORT }}

      # - name: Install PM2
      #   run: npm i pm2

      # - name: pulling
      #   run: git pull

      # - name: Deploy
      #   run: yarn pm2:restart
